#!/bin/bash

DIALOG () {
	dialog --backtitle "$TITLE" "$@"
	return $?
}

RSS_NAME="ITalialinux"
TITLE="Latest news from rss $RSS_NAME"
REMOTE_URL=http://www.italialinux.com/feed/

wget $REMOTE_URL -O rss.xml

#ITEMS=`xmllint --xpath //title/text() rss.xml >tmpfile`
ITEMS=`echo 'cat  //title/text()' | xmllint --shell  rss.xml `
echo "$ITEMS" > tmpfile
INPUT=""
while read LINE
do
	case $LINE in
	    '/ >'*|---*|'/ > '*)
	          continue;;
	    esac
#	echo "1 $LINE "
	INPUT="$INPUT  1 `echo "$LINE"` "
done < tmpfile
echo $INPUT
#DIALOG --menu "Latest news " 30 20 30 "$INPUT"
