#!/bin/bash

function usage(){
	echo "Usage: "
	echo "$0 -e extension [options]"
	echo "Default extension is wav"
	echo "Options: "
	echo "-d destinationfolder"
	echo "-h show this help"
}


if [ $# -lt 1 ] 
then
	usage
	exit 1
fi

FORMAT="wav"
DESTINATION=""
while getopts "e:hd:" OPTION
do
	case "$OPTION" in 
	h)
		usage
		exit 1
		;;
	d)	
		DESTINATION="$OPTARG"		
		;;
	e)
		FORMAT="$OPTARG"
		echo "$OPTARG"
		;;
	esac
done

echo $LOGFILE 
for f in *.$FORMAT
do 
	newname=`echo "$f"|sed "s/\.$FORMAT$//"`
	echo "Converting $f in .mp3"
	result=`ffmpeg -i "$f" "$DESTINATION""$newname".mp3 2>conversion.log` 
done

