#! /bin/bash
#Vhost creator script
#Vers 0.0.1 by Ivan

function usage(){
	echo "Usage: $0 foldername url vhostip"
}
clear
if [ $# -lt 2 ] 
then
	usage
	exit 1
else
	echo $1 " -  " $2
	sed "s/@1/$1/g;s/@2/$2/g" vhost.template
	exit 0
fi
