#! /bin/bash
#Vhost creator script
#Vers 0.0.1 by Ivan

function usage(){
	echo "Usage: $0 foldername url"
}
clear
if [ $# -lt 2 ] 
then
	usage
	exit 1
else
	cat vhost.template | while read line
	do 
		echo "${line}" | sed "s/\@1/$1/g;s/\@2/$2/g"\ 
	done
	exit 0
fi
